### ISSUE TITLE
deleting a namespace that has a cluster does not actually delete the cluster

### ISSUE THREAD

**Issue by jshimko** [samsung-cnct/krak8s#8]
When you delete a namespace that has a cluster associated with it, the cluster resource is deleted from krak8s as expected, but it doesn't actually delete anything from AWS.

### Setup

- create project
- create namespace in that project
- create cluster in that namespace

### Reproduction

- delete the namespace
- note that both namespace and cluster have been deleted
- go to AWS and note all servers still running

**Comment by sostheim** [comment]
Verified.

**Comment by sostheim** [comment]
The delete action was received and the action triggered successfully.
```
2017/09/08 13:54:07 [INFO] started req_id=TTOK2fGUlZ-20 DELETE=/v1/projects/91a98052/namespaces/5c638bcf from=127.0.0.1 ctrl=NamespaceController action=delete
2017/09/08 13:54:07 [INFO] headers req_id=TTOK2fGUlZ-20 Connection=close User-Agent=Paw/3.1.3 (Macintosh; OS X/10.12.6) GCDHTTPRequest
2017/09/08 13:54:07 [INFO] params req_id=TTOK2fGUlZ-20 namespaceid=5c638bcf projectid=91a98052
2017/09/08 13:54:07 [INFO] completed req_id=TTOK2fGUlZ-20 status=204 bytes=0 time=55.581µs ctrl=NamespaceController action=delete
I0908 13:54:07.122302       1 api_datastore.go:220] successfully archived persistent API state udpate.
I0908 13:54:07.122805       1 api_datastore.go:220] successfully archived persistent API state udpate.
```
The `git-archivist` updates were recorded shortly after the state updated.

```
I0908 14:29:59.807362       1 ga_service.go:91] commit updates at: 2017-09-08 14:29:59.80735311 +0000 UTC
I0908 14:29:59.814338       1 ga_service.go:82] push updates at: 2017-09-08 14:29:59.814333514 +0000 UTC
```
The kraken `./bin/update.sh --rmnodepools` run successfully and completed without an error response 3m30s later.   The `git-archivist` updated the configuration state accordingly.
```
I0908 14:31:04.398599       1 ga_service.go:91] commit updates at: 2017-09-08 14:31:04.398593327 +0000 UTC
I0908 14:31:04.415158       1 ga_service.go:82] push updates at: 2017-09-08 14:31:04.415153783 +0000 UTC
```
And the node pool resources were successfully removed from the running cluster:
```
 kubectl get nodes -l nodepool=jertestNodes
No resources found.
```  
For comparison, this is what a running node pool looks like in terms of the running cluster resources.
```
$ kubectl get nodes -l nodepool=jertest2Nodes
NAME                                        STATUS    AGE       VERSION
ip-10-0-169-72.us-west-2.compute.internal   Ready     5h        v1.6.4
ip-10-0-192-31.us-west-2.compute.internal   Ready     5h        v1.6.4
ip-10-0-6-32.us-west-2.compute.internal     Ready     4h        v1.6.4
ip-10-0-69-164.us-west-2.compute.internal   Ready     5h        v1.6.4
```
However, as noted in the ticket description, the ASG for the NodePool is still very much alive and owns 4 EC2 instances.

**Comment by sostheim** [comment]
API datastore.json diff checked and verified.
[git-archivist: auto update: 2017-09-08 13:54:48.297239391 +0000 UTC](https://github.com/reactioncommerce/colonybead-state/commit/c0d99745454867509d43753c9c1c5c17e1770cef)
visual diff: https://jsoncompare.com/#!/diff/id=f8829983b0bf9933311fdbe91f482190&fullscreen/

**Comment by sostheim** [comment]
There is no `git-archivist` update for what should be an accompanying update to the `config.yaml` for the cluster.  

Checking the system's active `config.yaml` file we see that the node pool specification is still present even though it's been deleted from the API server and the running cluster.
```
# grep jertest config.yaml -A 7
        - name: jertesterNodes
          count: 4
          kubeConfig: *colonybeadKube
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: 
            << : *defaultAwsClusterNode
            taints:
              - key: node-role.kubernetes.io/jertester
                value: jertester
                effect: NoSchedule
          keyPair: *colonybeadKeyPair
```
