### ISSUE TITLE
Improve Dup Checking Solution for Projects and Namespaces

### ISSUE THREAD

**Issue by sostheim** [samsung-cnct/krak8s#9]
Currently the system does a very simple, to simple, brute force search for duplicate terms in the kraken configuration files.  If a duplicate is detected, the action is rejected.

1) Need to improve the communication of the status on a duplicate instance to the client

2) Need to improve the fidelity of checking for duplicate names to understand the object and it's context before rejecting the action.

**Comment by sostheim** [comment]
Example:

Attempting to add the project/namespace `acme` is rejected for a completely unnecessary reason (a textual match), on string `acme` due to the following stanza in the configuration file.

```
        - name: kube-lego
          registry: quay.io
          chart: samsung_cnct/kube-lego
          version: '0.0.5-0'
          namespace: ingress
          values:
            image: "jetstack/kube-lego:0.1.4"
            email: letsencrypt@reactioncommerce.com
            domain: launchdock.io
            # api: "https://acme-colonybead.api.letsencrypt.org/directory"
            api: "https://acme-v01.api.letsencrypt.org/directory"
```
